integer, external :: gptlinitialize
integer, external :: gptlstart
integer, external :: gptlstop
integer, external :: gptlget_nregions
integer, external :: gptlget_regionname
integer, external :: gptlget_wallclock
integer, external :: gptlpr
integer, external :: gptlprint_memusage
integer, external :: gptlget_memusage
integer, external :: gptlpr_summary
integer, external :: gptlprint_rusage

external gptlprocess_namelist
